apiVersion: v1
kind: Service
metadata:
  name: hello-a-service
  labels:
    run: hello-a
spec:
  selector:
    run: hello-a
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
